### ISSUE TITLE
When filter is clicked returns to home rather than adjusting results

### ISSUE THREAD

**Issue by Wytchcat** [rvalitov/widgetkit-slidesetlightbox#7]
Installed in Widgetkit section of Warp 7 theme as adding by instructions leads to a 500 error.

When text filters set and tags added when you click the filter navigation it kicks back to the home page rather than sorting.

See:
http://capturethewest.com/index.php/captures

Joomla 3.7.2
Zoo 3.3.26
Widgetkit 2.9.8
Venice Warp theme Warp 7.3.34

**Comment by rvalitov** [comment]
Hi! 
1) Regarding your first question about the 500 error, please, provide the error log from the Apache, which can explain the reason of this problem.
2) Regarding the second question about the filter tags problem, the reason is that you have an overlapping `<p>` tag which covers the filter navigation bar and prevents correct navigation processing by the widget. This tag belongs to the Logo, so you just need to open the Logo module in Joomla and remove the unnecessary `<p>` tag. This tag is marked on the screenshot below and you can see it in the DOM tree:

![image](https://user-images.githubusercontent.com/16267156/28407798-13fbe436-6d3e-11e7-8819-1602cde53ab8.png)

I recommend to use a plain editor to edit the Logo module, actually, it should contain image only (`<img>` tag) without any other tags or containers. Probably, you use JCE Editor or something like that, which adds the unnecessary `<p>` tags automatically.

If you remove the `<p>` tags, then everything works fine:

![tags](https://user-images.githubusercontent.com/16267156/28407875-6724b23c-6d3e-11e7-8db5-cd099728efdc.gif)

Please, let me know if this helps and looking forward to receive the error.log file from Apache to solve your first problem.

**Comment by rvalitov** [comment]
No response from user, this issue is closed.
